import type { Ingredient } from "./types";

export const INGREDIENTS: Ingredient[] = [
  {
    id: "brown-butter-cake",
    name: "Brown-butter pound cake",
    layer: "base",
    tags: ["nostalgic", "rich", "seasonal"],
    cost: 0.62,
    quality: 5,
    allergen: "gluten",
    local: true,
    color: "#c4a574",
    note: "Baked in-house Tuesday and Friday.",
  },
  {
    id: "gingerbread",
    name: "Gingerbread crumbs",
    layer: "base",
    tags: ["spicy", "nostalgic", "seasonal"],
    cost: 0.48,
    quality: 4,
    allergen: "gluten",
    local: true,
    color: "#8b5a2b",
    note: "Molasses-dark, from Grandma's own tin.",
  },
  {
    id: "brioche",
    name: "Toasted brioche cubes",
    layer: "base",
    tags: ["rich", "nostalgic", "photogenic"],
    cost: 0.55,
    quality: 4,
    allergen: "gluten",
    local: true,
    color: "#e8c58a",
    note: "Day-old loaves, never wasted.",
  },
  {
    id: "maple-oat",
    name: "Maple oat crumble",
    layer: "base",
    tags: ["healthy", "light", "seasonal"],
    cost: 0.4,
    quality: 4,
    allergen: "gluten",
    local: true,
    color: "#c98646",
    note: "Rolled oats from Hartwell Mill.",
  },
  {
    id: "pumpkin-bread",
    name: "Pumpkin spice bread",
    layer: "base",
    tags: ["sweet", "seasonal", "bakeryClone", "nostalgic"],
    cost: 0.44,
    quality: 3,
    allergen: "gluten",
    local: false,
    color: "#d4924a",
    note: "Tastes a little too close to next door.",
  },
  {
    id: "roasted-squash",
    name: "Roasted squash cubes",
    layer: "base",
    tags: ["seasonal", "healthy", "light"],
    cost: 0.38,
    quality: 4,
    local: true,
    color: "#e0a04a",
    note: "No wheat. Still tastes like October.",
  },
  {
    id: "maple-mascarpone",
    name: "Maple mascarpone",
    layer: "cream",
    tags: ["creamy", "sweet", "rich", "seasonal"],
    cost: 0.92,
    quality: 5,
    allergen: "dairy",
    local: true,
    color: "#f3ead6",
    note: "Meadowdale mascarpone, local maple.",
  },
  {
    id: "brown-butter-custard",
    name: "Brown-butter custard",
    layer: "cream",
    tags: ["creamy", "rich", "nostalgic", "novel"],
    cost: 0.88,
    quality: 5,
    allergen: "dairy",
    local: true,
    color: "#f0d48a",
    note: "Nutty, slow-cooked, unmistakably Grandma.",
  },
  {
    id: "cinnamon-yogurt",
    name: "Cinnamon Greek yogurt",
    layer: "cream",
    tags: ["creamy", "healthy", "light", "tart"],
    cost: 0.52,
    quality: 4,
    allergen: "dairy",
    local: true,
    color: "#f7f1e6",
    note: "Tang that keeps a second spoon coming.",
  },
  {
    id: "chai-cream",
    name: "Chai whipped cream",
    layer: "cream",
    tags: ["creamy", "spicy", "novel", "photogenic"],
    cost: 0.7,
    quality: 4,
    allergen: "dairy",
    local: true,
    color: "#e6d0b0",
    note: "Cardamom, clove, black tea.",
  },
  {
    id: "honey-ricotta",
    name: "Honey ricotta",
    layer: "cream",
    tags: ["creamy", "light", "floral", "healthy"],
    cost: 0.66,
    quality: 5,
    allergen: "dairy",
    local: true,
    color: "#f6f0e4",
    note: "From Willow Brook dairy, clover honey.",
  },
  {
    id: "vanilla-whip",
    name: "Vanilla whipped cream",
    layer: "cream",
    tags: ["creamy", "sweet", "bakeryClone", "photogenic"],
    cost: 0.38,
    quality: 3,
    allergen: "dairy",
    local: false,
    color: "#fffaf3",
    note: "The Bakery's default cloud.",
  },
  {
    id: "pumpkin-mousse",
    name: "Pumpkin spice mousse",
    layer: "cream",
    tags: ["sweet", "spicy", "seasonal", "bakeryClone", "rich"],
    cost: 0.6,
    quality: 3,
    allergen: "dairy",
    local: false,
    color: "#e09a4a",
    note: "If you close your eyes, you're next door.",
  },
  {
    id: "coconut-cloud",
    name: "Coconut cloud",
    layer: "cream",
    tags: ["creamy", "light", "floral", "novel"],
    cost: 0.58,
    quality: 4,
    local: false,
    color: "#f7f3ea",
    note: "Whipped coconut. No dairy in the glass.",
  },
  {
    id: "apple-butter",
    name: "Spiced apple butter",
    layer: "cream",
    tags: ["seasonal", "nostalgic", "sweet", "fruit"],
    cost: 0.46,
    quality: 5,
    local: true,
    color: "#b35a2a",
    note: "From Lane's. Spreads like a secret.",
  },
  {
    id: "honeycrisp",
    name: "Honeycrisp compote",
    layer: "fruit",
    tags: ["fruit", "tart", "seasonal", "nostalgic", "photogenic"],
    cost: 0.58,
    quality: 5,
    local: true,
    color: "#d45a3a",
    note: "Orchard three towns over. Peak October.",
  },
  {
    id: "roasted-pear",
    name: "Roasted pear",
    layer: "fruit",
    tags: ["fruit", "seasonal", "nostalgic", "floral"],
    cost: 0.64,
    quality: 5,
    local: true,
    color: "#c9b46a",
    note: "Bosc pears, roasted with thyme.",
  },
  {
    id: "cranberry",
    name: "Cranberry-orange relish",
    layer: "fruit",
    tags: ["fruit", "tart", "seasonal", "photogenic", "novel"],
    cost: 0.5,
    quality: 4,
    local: true,
    color: "#a61e2d",
    note: "Bright enough to wake a 8am lecture.",
  },
  {
    id: "spiced-plum",
    name: "Spiced plum",
    layer: "fruit",
    tags: ["fruit", "novel", "spicy", "photogenic"],
    cost: 0.72,
    quality: 5,
    local: false,
    color: "#7a3b5c",
    note: "Star anise and black pepper.",
  },
  {
    id: "roasted-fig",
    name: "Roasted fig",
    layer: "fruit",
    tags: ["fruit", "novel", "floral", "rich", "photogenic"],
    cost: 0.95,
    quality: 5,
    local: false,
    color: "#5c3a4e",
    note: "A little fancy. Worth it for a date.",
  },
  {
    id: "persimmon",
    name: "Fuyu persimmon",
    layer: "fruit",
    tags: ["fruit", "novel", "seasonal", "photogenic", "light"],
    cost: 0.8,
    quality: 4,
    local: false,
    color: "#e07a2f",
    note: "Honeyed, rare on this block.",
  },
  {
    id: "pumpkin-puree",
    name: "Pumpkin puree",
    layer: "fruit",
    tags: ["seasonal", "sweet", "bakeryClone", "nostalgic"],
    cost: 0.32,
    quality: 3,
    local: false,
    color: "#e8883a",
    note: "The Bakery's Autumn Parfait backbone.",
  },
  {
    id: "candied-pecan",
    name: "Candied pecans",
    layer: "crunch",
    tags: ["crunchy", "nutty", "sweet", "nostalgic"],
    cost: 0.54,
    quality: 5,
    allergen: "nuts",
    local: true,
    color: "#6b3e1f",
    note: "Sugared in the copper pot.",
  },
  {
    id: "hazelnut",
    name: "Toasted hazelnuts",
    layer: "crunch",
    tags: ["crunchy", "nutty", "novel", "rich"],
    cost: 0.7,
    quality: 5,
    allergen: "nuts",
    local: false,
    color: "#8a5a32",
    note: "Skinned and warm.",
  },
  {
    id: "pepita",
    name: "Maple pepitas",
    layer: "crunch",
    tags: ["crunchy", "healthy", "seasonal", "light"],
    cost: 0.42,
    quality: 4,
    local: true,
    color: "#7a8f3d",
    note: "No nuts. Still a snap.",
  },
  {
    id: "gingersnap",
    name: "Gingersnap shards",
    layer: "crunch",
    tags: ["crunchy", "spicy", "nostalgic", "seasonal"],
    cost: 0.36,
    quality: 4,
    allergen: "gluten",
    local: true,
    color: "#a0673a",
    note: "Snaps from the morning bake.",
  },
  {
    id: "streusel",
    name: "Brown-butter streusel",
    layer: "crunch",
    tags: ["crunchy", "rich", "nostalgic", "novel"],
    cost: 0.46,
    quality: 5,
    allergen: "gluten",
    local: true,
    color: "#c49a5a",
    note: "The smell that stops sidewalk traffic.",
  },
  {
    id: "cacao-nib",
    name: "Cacao nibs",
    layer: "crunch",
    tags: ["crunchy", "chocolate", "bitter", "novel"],
    cost: 0.6,
    quality: 4,
    local: false,
    color: "#3d2a1f",
    note: "For people who say they don't like dessert.",
  },
  {
    id: "store-granola",
    name: "Bagged autumn granola",
    layer: "crunch",
    tags: ["crunchy", "bakeryClone", "sweet"],
    cost: 0.28,
    quality: 2,
    allergen: "gluten",
    local: false,
    color: "#b8956a",
    note: "The Bakery pours this from a sack.",
  },
  {
    id: "dark-caramel",
    name: "Dark caramel",
    layer: "drizzle",
    tags: ["sweet", "rich", "photogenic"],
    cost: 0.34,
    quality: 5,
    local: true,
    color: "#c4782a",
    note: "Taken to the edge, then stopped.",
  },
  {
    id: "sorghum",
    name: "Sorghum molasses",
    layer: "drizzle",
    tags: ["novel", "nostalgic", "rich"],
    cost: 0.3,
    quality: 5,
    local: true,
    color: "#5c3a1e",
    note: "From a farm stand Grandma trusts.",
  },
  {
    id: "bourbon-maple",
    name: "Bourbon maple",
    layer: "drizzle",
    tags: ["sweet", "novel", "rich", "seasonal"],
    cost: 0.48,
    quality: 5,
    local: true,
    color: "#b4531e",
    note: "A splash. Not a gimmick.",
  },
  {
    id: "cider-reduction",
    name: "Apple cider reduction",
    layer: "drizzle",
    tags: ["tart", "seasonal", "fruit", "nostalgic"],
    cost: 0.36,
    quality: 5,
    local: true,
    color: "#c45c2a",
    note: "Reduced until it coats a spoon.",
  },
  {
    id: "espresso-ganache",
    name: "Espresso ganache",
    layer: "drizzle",
    tags: ["chocolate", "coffee", "bitter", "rich", "novel"],
    cost: 0.52,
    quality: 5,
    allergen: "dairy",
    local: true,
    color: "#2b1a12",
    note: "For the midterm crowd.",
  },
  {
    id: "cheap-caramel",
    name: "Squeeze-bottle caramel",
    layer: "drizzle",
    tags: ["sweet", "bakeryClone"],
    cost: 0.14,
    quality: 1,
    local: false,
    color: "#d4923a",
    note: "Tastes like the lid.",
  },
  {
    id: "orange-peel",
    name: "Candied orange peel",
    layer: "garnish",
    tags: ["photogenic", "floral", "tart", "novel"],
    cost: 0.18,
    quality: 5,
    local: true,
    color: "#e8833a",
    note: "Little jewels on top.",
  },
  {
    id: "sage",
    name: "Fried sage",
    layer: "garnish",
    tags: ["novel", "photogenic", "seasonal"],
    cost: 0.12,
    quality: 5,
    local: true,
    color: "#7a8f6a",
    note: "Savory wink. Very Grandma.",
  },
  {
    id: "marigold",
    name: "Edible marigold",
    layer: "garnish",
    tags: ["photogenic", "floral", "novel"],
    cost: 0.22,
    quality: 4,
    local: true,
    color: "#e8a020",
    note: "First-date insurance.",
  },
  {
    id: "cinnamon-stick",
    name: "Cinnamon stick",
    layer: "garnish",
    tags: ["spicy", "nostalgic", "seasonal", "bakeryClone"],
    cost: 0.1,
    quality: 3,
    local: false,
    color: "#8b4513",
    note: "Pretty. Predictable.",
  },
  {
    id: "cream-dollop",
    name: "Extra whipped dollop",
    layer: "garnish",
    tags: ["creamy", "sweet", "bakeryClone"],
    cost: 0.12,
    quality: 3,
    allergen: "dairy",
    local: false,
    color: "#fff8ee",
    note: "The Bakery puts two.",
  },
];

export const INGREDIENT_MAP = Object.fromEntries(
  INGREDIENTS.map((ingredient) => [ingredient.id, ingredient]),
) as Record<string, Ingredient>;

export function getIngredient(id: string): Ingredient {
  const ingredient = INGREDIENT_MAP[id];
  if (!ingredient) {
    throw new Error(`Unknown ingredient: ${id}`);
  }
  return ingredient;
}

export const LAYERS: Ingredient["layer"][] = [
  "base",
  "cream",
  "fruit",
  "crunch",
  "drizzle",
  "garnish",
];
